### ISSUE TITLE
the service is being discontinued.  For all future markets and equities data research

### ISSUE THREAD

**Issue by moiroca** [ojhaujjwal/currency-converter-php#12]
the service is being discontinued.  For all future markets and equities data research

**Comment by ojhaujjwal** [comment]
We got a PR a few days depending on fixer.io.
https://github.com/ojhaujjwal/currency-converter-php/pull/11

It's in progress.
We will hope to complete it soon, in the next few days.

**Comment by moiroca** [comment]
@ojhaujjwal What do you recommend?

**Comment by ojhaujjwal** [comment]
yeah, it should.

**Comment by slavielle** [comment]
I see the PR has been merged in the dev-master branch. Do you think you would be able releasing a stable version soon in order to be able to have the new provider available using a simple composer update ?

Many thanks

**Comment by ojhaujjwal** [comment]
Done! I have released.
Thanks for the reminder.

**Comment by slavielle** [comment]
That was quick :) thanks a lot

**Comment by slavielle** [comment]
Would this issue be closed ?
