### ISSUE TITLE
Test seems to fail on PHP 5.4

### ISSUE THREAD

**Issue by slavielle** [ojhaujjwal/currency-converter-php#14]
Accordingly to travis report (https://travis-ci.org/ojhaujjwal/currency-converter-php) your tests seem to fail on PHP 5.4. It would be better to skip tests for 5.4 in your .travis.yml and officially support form PHP 5.5 only.

**Comment by ojhaujjwal** [comment]
I should have done it before the release. Do you mind sending a PR and I will release a patch version

**Comment by slavielle** [comment]
I'll do it in a few hours

**Comment by slavielle** [comment]
done :)
