### ISSUE TITLE
Better Exception on FixerApi.php provider

### ISSUE THREAD

**Issue by slavielle** [ojhaujjwal/currency-converter-php#16]
When I try to get change rate for an existing but not supported (by fixer.io) currency such as  ANG (Netherlands Antilles Guilder) I finally get an exception caused by Undefined index ANG at /vendor/ujjwal/currency-converter/src/Provider/FixerApi.php line : 44:

Wouldn't it be better to throw a proper and catchable exception here ?

**Comment by ojhaujjwal** [comment]
correct. I like the idea. 
I am open to Pull Requests mate :D :P

**Comment by slavielle** [comment]
Hi :), how about this ?

**Comment by slavielle** [comment]
Hello ojhaujjwal

This PR still pending. I fixed what you pointed out in PR comments except for the Invalid/Unsupported currency exception where I still have a pending questions/remarks waiting for your reply. Would you mind have a look at it when you have time to ?

Many thanks

**Comment by slavielle** [comment]
hello ojhaujjwal. Mind you to release a stable version please ?

**Comment by slavielle** [comment]
hello ojhaujjwal. It would be great to release this one as a stable version ;)
