### ISSUE TITLE
Documentation refers to unsupported Yahoo API

### ISSUE THREAD

**Issue by slavielle** [ojhaujjwal/currency-converter-php#18]
> Reliable Rate, Uses Yahoo API
> Caching of rate, to avoid connecting to Yahoo again and again

Must be changed to Fixer.io API

**Comment by ojhaujjwal** [comment]
I am in a vacation right now. Do you mind sending a PR?

**Comment by slavielle** [comment]
Hello I'll do it shortly

**Comment by slavielle** [comment]
Well, not that shortly I'm afraid ... sorry for the delay ;) ... PR is done.
