### ISSUE TITLE
Fixer API endpoint is dead

### ISSUE THREAD

**Issue by jbrinksmeier** [ojhaujjwal/currency-converter-php#22]
The currently implemented endpoint of fixer is down: https://api.fixer.io/latest
Neccessary changes are documented here: https://github.com/fixerAPI/fixer

Besides the new endpoint (API is unchanged otherwise) users now need to signup for an account and provide an api-key to access their rates api.

I am working on a fix for this lib, but it will break BC as for the mentioned api key (well, this lib is useless in it's current state, anyway).

**Comment by lordcris** [comment]
I have substituted

const FIXER_API_BASEPATH = 'https://api.fixer.io/latest';

with

const FIXER_API_BASEPATH = 'https://exchangeratesapi.io/api/latest';

in /ujjwal/currency-converter/src/Provider/FixerApi.php

and everything works fine.

https://exchangeratesapi.io/

**Comment by jbrinksmeier** [comment]
thanks @lordcris I haven't been aware of exchangerates.io. It will be implemented in #23
