### ISSUE TITLE
When searching up an obsolete currency it throws an division by zero

### ISSUE THREAD

**Issue by Pecka40** [ojhaujjwal/currency-converter-php#9]
As the title says it, it throws an exception division by zero. You could just catch it and return 0. Of course the chance of someone looking up an obsolete currency is small but it wouldn't hurt if you added a check for it.

This did the trick:
try {
	return (1 / $this->getCacheAdapter()->getRate($toCurrency, $fromCurrency)) * $amount;
} catch(\Exception $e) {
	return 0;
}

I don't really know much about pull requests and so on. And I'm pretty new to PHP too.

**Comment by ojhaujjwal** [comment]
If catching exception works, how about doing this:
```php
try {
   $rate = $converter->convert($from, $to);
} catch(\Exception $e) {
   $rate = 0;
}
```

**Comment by Pecka40** [comment]
Yeah, that does the trick too i guess.
